### ISSUE TITLE
where is product.json 

### ISSUE THREAD

**Issue by sarangkkl** [CleverProgrammers/amazon-blockchain-youtube#1]
you promise that there will be product.json but i cant find it please upload product.json

**Comment by baotq610** [comment]
me too

**Comment by Zaid-maker** [comment]
Same

**Comment by Zaid-maker** [comment]
@sarangkkl here's the link, it was in description.
https://drive.google.com/drive/folders/1QSBFU2T7jtU7VueInXzs1vppJBm6Ie2e

**Comment by tirth3112** [comment]
In the sidebar I am creating an avatar with connecting button, there is no error code running well but at the end, the hydration error is a pop-up and the avatar is disappear.

![image](https://user-images.githubusercontent.com/60727851/167234878-c7fbe238-5b5d-467c-bcee-7ca2a1564cf0.png)
